// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTrips.Models;

#nullable disable

namespace ProjectTrips.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20220331174509_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectTrips.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"), 1L, 1);

                    b.Property<string>("AccommodationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccommodationPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accommodations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToDo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDo3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            AccommodationEmail = "None",
                            AccommodationPhone = "None",
                            Accommodations = "Botanical Garden w/ Fiance",
                            Destination = "Ohio",
                            End = new DateTime(2021, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDo1 = "Relax"
                        },
                        new
                        {
                            TripId = 2,
                            AccommodationEmail = "None",
                            AccommodationPhone = "None",
                            Accommodations = "RoadTrip",
                            Destination = "Texarkana, AK",
                            End = new DateTime(2021, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2021, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDo1 = "Relax"
                        },
                        new
                        {
                            TripId = 3,
                            AccommodationEmail = "kiyoshisuites@net.com",
                            AccommodationPhone = "111-1111-1111",
                            Accommodations = "Kiyoshi Hotel & Luxury Suites",
                            Destination = "Japan",
                            End = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2021, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDo1 = "Relax"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
